all:udp_client01 udp_server01 
udp_client01:udp_client01.o
	gcc -o udp_client01 udp_client01.o
udp_server01:udp_server01.o
	gcc -o udp_server01 udp_server01.o
clean:
	rm udp_client01 udp_server01 *.o -rf
    
